""" simple script to test playing an oct pulse generated by ecd control """

import time
from qm import qua

from qcrew.control import Stagehand

def play_oct_pulse(qubit, cavity):
    """ """
    with qua.program() as play_constant_pulse:
        with qua.infinite_loop_():
            qua.reset_frame(qubit.name, cavity.name)
            qubit.play("oct_pulse")
            cavity.play("oct_pulse")
            qua.wait(int(1e6))
    return play_constant_pulse


with Stagehand() as stage:
    qm = stage.QM
    job = qm.execute(play_oct_pulse(stage.QUBIT, stage.CAVITY))
    time.sleep(60)
    job.halt()
