- !<Qubit>
  name: QUBIT
  lo: LB_QUBIT
  int_freq: -1.000000E+08
  ports:
    I: 1
    Q: 2
  mixer_offsets:
    I: 0.00436572798062116
    Q: -0.0059232642408460386
    G: -0.17340511726215485
    P: 0.10656575898174203
  operations:
    constant_pulse: !<ConstantPulse>
      length: 1000
      ampx: 1.0
    gaussian_pulse: !<GaussianPulse>
      sigma: 100
      chop: 6
      ampx: 1.0
      drag: 0.0
    rotation_pulse: !<GaussianPulse>
      sigma: 10
      chop: 6
      ampx: 1.0
      drag: 0.0
  omegas: []
  rotation_ampxs:
    '0': 0.0
    pi2: 0.0
    pi: 0.0
- !<Readout>
  name: RR
  lo: LB_RR
  int_freq: -1.000000E+07
  ports:
    I: 4
    Q: 3
    out: 1
  mixer_offsets:
    I: -0.02863638913258911
    Q: 0.002603589789941911
    G: 0.2712895035743713
    P: -0.11136218905448916
    out: 0.0
  operations:
    constant_pulse: !<ConstantPulse>
      length: 1000
      ampx: 1.0
    gaussian_pulse: !<GaussianPulse>
      sigma: 100
      chop: 6
      ampx: 1.0
      drag: 0.0
    readout_pulse: !<ConstantPulse>
      length: 400
      ampx: 1.0
      integration_weights: !<ConstantIntegrationWeights>
        length: 100
        magnitude:
        - 1.0
        - 0.0
        - 0.0
        - 1.0
        is_pinned: true
  time_of_flight: 180
  smearing: 0
